# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day26.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
#video1        
        self.label_videoframe = QtWidgets.QLabel(self.centralwidget)
        self.label_videoframe.setGeometry(QtCore.QRect(150, 150, 400, 250))
        self.label_videoframe.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_videoframe.setObjectName("label_videoframe")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 150, 110, 200))
        self.groupBox.setObjectName("groupBox")


        # button for video 1
        self.button_openfile = QtWidgets.QPushButton(self.groupBox)
        self.button_openfile.setGeometry(QtCore.QRect(5, 50, 100, 30))
        self.button_openfile.setObjectName("button_openfile")
        
        #label for frmae count video1
        # self.label_framecnt = QtWidgets.QLabel(self.centralwidget)
        # self.label_framecnt.setGeometry(QtCore.QRect(830, 20, 300, 20))
        # self.label_framecnt.setObjectName("label_framecnt")

        # self.framecnt = QtWidgets.QLabel(self.centralwidget)
        # self.framecnt.setGeometry(QtCore.QRect(1600, 20, 600, 40))
        # self.framecnt.setObjectName("framecnt")

        # self.totalcnt = QtWidgets.QLabel(self.centralwidget)
        # # self.totalcnt.setGeometry(QtCore.QRect(1700, 20, 600, 40))
        # self.totalcnt.setObjectName("totalcnt")

        self.button_rewind = QtWidgets.QPushButton(self.groupBox)
        self.button_rewind.setGeometry(QtCore.QRect(5, 90, 30, 30))
        self.button_rewind.setObjectName("button_rewind")
        self.button_rewind.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/rewind.png"))
        self.button_rewind.setIconSize(QtCore.QSize(30,30))

        self.button_play = QtWidgets.QPushButton(self.groupBox)
        self.button_play.setGeometry(QtCore.QRect(35, 90, 30, 30))
        self.button_play.setObjectName("button_play")
        self.button_play.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/play.jpg"))
        self.button_play.setIconSize(QtCore.QSize(30,30))

        self.button_pause = QtWidgets.QPushButton(self.groupBox)
        self.button_pause.setGeometry(QtCore.QRect(35, 120, 30, 30))
        self.button_pause.setObjectName("button_pause")
        self.button_pause.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/pause.jpg"))
        self.button_pause.setIconSize(QtCore.QSize(30,30))

        self.button_forward = QtWidgets.QPushButton(self.groupBox)
        self.button_forward.setGeometry(QtCore.QRect(65, 90, 30, 30))
        self.button_forward.setObjectName("button_forward")
        self.button_forward.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/forward.jpg"))
        self.button_forward.setIconSize(QtCore.QSize(30,30))
 
        self.button_stop = QtWidgets.QPushButton(self.groupBox)
        self.button_stop.setGeometry(QtCore.QRect(5, 150, 100, 30))
        self.button_stop.setObjectName("button_stop")
        
        self.label_filepath = QtWidgets.QLabel(self.centralwidget)
        self.label_filepath.setGeometry(QtCore.QRect(10, 80, 640, 40))
        self.label_filepath.setObjectName("label_filepath")

        self.slider_videoframe = QtWidgets.QSlider(self.centralwidget)
        self.slider_videoframe.setGeometry(QtCore.QRect(150, 110, 400, 40))
        self.slider_videoframe.setOrientation(QtCore.Qt.Horizontal)
        self.slider_videoframe.setObjectName("slider_videoframe")

        self.slider_videoframe3 = QtWidgets.QSlider(self.centralwidget)
        self.slider_videoframe3.setGeometry(QtCore.QRect(970, 830, 640, 40))
        self.slider_videoframe3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_videoframe3.setObjectName("slider_videoframe")


        self.button_process = QtWidgets.QPushButton(self.centralwidget)
        self.button_process.setGeometry(QtCore.QRect(15, 900, 240, 60))
        self.button_process.setObjectName("button_process")
        
        self.button_showimg = QtWidgets.QPushButton(self.centralwidget)
        self.button_showimg.setGeometry(QtCore.QRect(255, 900, 240, 60))
        self.button_showimg.setObjectName("button_image")

# groupbox for bat
        self.Bat_group_box_name = QtWidgets.QLabel(self.centralwidget)
        self.Bat_group_box_name.setGeometry(QtCore.QRect(10, 240, 560, 380))
        self.Bat_group_box_name.setObjectName("bat_group_name")

        self.groupbox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox2.setGeometry(QtCore.QRect(10, 450, 560, 180))
        self.groupbox2.setObjectName("groupBox_bat")

        self.swing_time_lb_outcome = QtWidgets.QLabel(self.groupbox2)
        self.swing_time_lb_outcome.setGeometry(QtCore.QRect(330, 130, 200, 50))
        self.swing_time_lb_outcome.setObjectName("swing_time_outcome")

        self.swing_time_lb_outcome_unit = QtWidgets.QLabel(self.groupbox2)
        self.swing_time_lb_outcome_unit.setGeometry(QtCore.QRect(470, 130, 200, 50))
        self.swing_time_lb_outcome_unit.setObjectName("swing_time_outcome_unit")

        self.bat_speed_lb_outcome = QtWidgets.QLabel(self.groupbox2)
        self.bat_speed_lb_outcome.setGeometry(QtCore.QRect(330, 10, 200, 50))
        self.bat_speed_lb_outcome.setObjectName("ball_speed_outcome")

        self.bat_speed_lb_outcome_unit = QtWidgets.QLabel(self.groupbox2)
        self.bat_speed_lb_outcome_unit.setGeometry(QtCore.QRect(470, 10, 200, 50))
        self.bat_speed_lb_outcome_unit.setObjectName("ball_speed_outcome_unit")

        self.swing_angle_lb_outcome = QtWidgets.QLabel(self.groupbox2)
        self.swing_angle_lb_outcome.setGeometry(QtCore.QRect(330, 70, 200, 50))
        self.swing_angle_lb_outcome.setObjectName("swing_angle_outcome")

        self.swing_angle_lb_outcome_unit = QtWidgets.QLabel(self.groupbox2)
        self.swing_angle_lb_outcome_unit.setGeometry(QtCore.QRect(470, 70, 200, 50))
        self.swing_angle_lb_outcome_unit.setObjectName("swing_angle_outcome_unit")

        self.swing_time_lb = QtWidgets.QLabel(self.groupbox2)
        self.swing_time_lb.setGeometry(QtCore.QRect(10, 130, 200, 50))
        self.swing_time_lb.setObjectName("swing_time")

        self.bat_speed_lb = QtWidgets.QLabel(self.groupbox2)
        self.bat_speed_lb.setGeometry(QtCore.QRect(10, 10, 240, 50))
        self.bat_speed_lb.setObjectName("bat_speed")

        self.swing_angle_lb = QtWidgets.QLabel(self.groupbox2)
        self.swing_angle_lb.setGeometry(QtCore.QRect(10, 70, 240, 50))
        self.swing_angle_lb.setObjectName("swing_angle")

# bat的groupbox到500
# groupbox for ball

        self.Ball_group_box_name = QtWidgets.QLabel(self.centralwidget)
        self.Ball_group_box_name.setGeometry(QtCore.QRect(10, 480, 560, 380))
        self.Ball_group_box_name.setObjectName("ball_group_name")

        self.groupbox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox3.setGeometry(QtCore.QRect(10, 690, 560, 180))
        self.groupbox3.setObjectName("groupBox_ball")


        self.ball_exit_speed_lb_outcome = QtWidgets.QLabel(self.groupbox3)
        self.ball_exit_speed_lb_outcome.setGeometry(QtCore.QRect(330, 10, 200, 50))
        self.ball_exit_speed_lb_outcome.setObjectName("ball_exit_speed_outcome")

        self.ball_exit_speed_lb_outcome_unit = QtWidgets.QLabel(self.groupbox3)
        self.ball_exit_speed_lb_outcome_unit.setGeometry(QtCore.QRect(470, 10, 200, 50))
        self.ball_exit_speed_lb_outcome_unit.setObjectName("ball_exit_speed_outcome_unit")

        self.ball_exit_angle_lb_outcome = QtWidgets.QLabel(self.groupbox3)
        self.ball_exit_angle_lb_outcome.setGeometry(QtCore.QRect(330, 70, 200, 50))
        self.ball_exit_angle_lb_outcome.setObjectName("ball_exit_angle_outcome")

        self.ball_exit_angle_lb_outcome_unit = QtWidgets.QLabel(self.groupbox3)
        self.ball_exit_angle_lb_outcome_unit.setGeometry(QtCore.QRect(470, 70, 200, 50))
        self.ball_exit_angle_lb_outcome_unit.setObjectName("ball_exit_angle_outcome_unit")

        self.projected_dis_lb_outcome = QtWidgets.QLabel(self.groupbox3)
        self.projected_dis_lb_outcome.setGeometry(QtCore.QRect(330, 130, 200, 50))
        self.projected_dis_lb_outcome.setObjectName("projected_dis_outcome")

        self.projected_dis_lb_outcome_unit = QtWidgets.QLabel(self.groupbox3)
        self.projected_dis_lb_outcome_unit.setGeometry(QtCore.QRect(470, 130, 40, 50))
        self.projected_dis_lb_outcome_unit.setObjectName("projected_dis_unit")

        self.ball_exit_speed_lb = QtWidgets.QLabel(self.groupbox3)
        self.ball_exit_speed_lb.setGeometry(QtCore.QRect(10, 10, 240, 50))
        self.ball_exit_speed_lb.setObjectName("ball_exit_speed")

        self.ball_exit_angle_lb = QtWidgets.QLabel(self.groupbox3)
        self.ball_exit_angle_lb.setGeometry(QtCore.QRect(10, 70, 240, 50))
        self.ball_exit_angle_lb.setObjectName("ball_exit_angle")

        self.projected_dis_lb = QtWidgets.QLabel(self.groupbox3)
        self.projected_dis_lb.setGeometry(QtCore.QRect(10, 130, 240, 50))
        self.projected_dis_lb.setObjectName("ball_exit_angle")

        self.groupbox4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox4.setGeometry(QtCore.QRect(600, 810, 330, 100))
        self.groupbox4.setObjectName("groupbox4")

        #button for video 
        self.button_openfile3 = QtWidgets.QPushButton(self.groupbox4)
        self.button_openfile3.setGeometry(QtCore.QRect(5, 20, 100, 30))
        self.button_openfile3.setObjectName("button_openfile3")

        self.label_videoframe3 = QtWidgets.QLabel(self.centralwidget)
        self.label_videoframe3.setGeometry(QtCore.QRect(600, 90, 1280, 720))
        self.label_videoframe3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_videoframe3.setObjectName("label_videoframe3")

        #label for frmae count video1
        # self.label_framecnt2 = QtWidgets.QLabel(self.centralwidget)
        # self.label_framecnt2.setGeometry(QtCore.QRect(1300, 910, 600, 30))
        # self.label_framecnt2.setObjectName("label_framecnt")

        # self.framecnt2 = QtWidgets.QLabel(self.centralwidget)
        # self.framecnt2.setGeometry(QtCore.QRect(1600, 910, 600, 40))
        # self.framecnt2.setObjectName("framecnt2")

        # self.totalcnt2 = QtWidgets.QLabel(self.centralwidget)
        # self.totalcnt2.setGeometry(QtCore.QRect(1700, 910, 600, 40))
        # self.totalcnt2.setObjectName("totalcnt2")
        
        self.button_rewind3 = QtWidgets.QPushButton(self.groupbox4)
        self.button_rewind3.setGeometry(QtCore.QRect(105, 30, 50, 50))
        self.button_rewind3.setObjectName("button_rewind")
        self.button_rewind3.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/rewind.png"))
        self.button_rewind3.setIconSize(QtCore.QSize(50,50))

        self.button_play3 = QtWidgets.QPushButton(self.groupbox4)
        self.button_play3.setGeometry(QtCore.QRect(155, 30, 50, 50))
        self.button_play3.setObjectName("button_play")
        self.button_play3.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/play.jpg"))
        self.button_play3.setIconSize(QtCore.QSize(50,50))

        self.button_pause3 = QtWidgets.QPushButton(self.groupbox4)
        self.button_pause3.setGeometry(QtCore.QRect(210, 30, 50, 50))
        self.button_pause3.setObjectName("button_pause")
        self.button_pause3.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/pause.jpg"))
        self.button_pause3.setIconSize(QtCore.QSize(50,50))

        self.button_forward3 = QtWidgets.QPushButton(self.groupbox4)
        self.button_forward3.setGeometry(QtCore.QRect(265, 30, 50, 50))
        self.button_forward3.setObjectName("button_forward")
        self.button_forward3.setIcon(QtGui.QIcon("D:/1122/專題/swim/video/icons/forward.jpg"))
        self.button_forward3.setIconSize(QtCore.QSize(50,50))

        self.button_stop3 = QtWidgets.QPushButton(self.groupbox4)
        self.button_stop3.setGeometry(QtCore.QRect(5, 60, 100, 30))
        self.button_stop3.setObjectName("button_stop")
#(930, 360, 800, 450)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video"))
        
        self.label_videoframe.setText(_translate("MainWindow", "輸入影片"))
        self.label_videoframe3.setText(_translate("MainWindow", "分析結果"))
        self.label_videoframe.setFont(QtGui.QFont("Arial", 50))
        self.label_videoframe3.setFont(QtGui.QFont("Arial", 50))

        self.button_openfile.setText(_translate("MainWindow", "打開影片"))
        self.button_openfile.setFont(QtGui.QFont("Arial", 10))

        self.button_stop.setText(_translate("MainWindow", "影片開頭"))
        self.button_stop.setFont(QtGui.QFont("Arial",10))
        
        self.label_filepath.setText(_translate("MainWindow", "影片地址:"))
        self.label_filepath.setFont(QtGui.QFont("Arial", 8))

        self.button_openfile3.setText(_translate("MainWindow", "打開結果"))
        self.button_openfile3.setFont(QtGui.QFont("Arial", 10))

        self.button_stop3.setText(_translate("MainWindow", "結果開頭"))
        self.button_stop3.setFont(QtGui.QFont("Arial", 10))

        self.button_process.setText(_translate("MainWindow", "process"))
        self.button_process.setFont(QtGui.QFont("Arial", 20))

        self.button_showimg.setText(_translate("MainWindow", "image"))
        self.button_showimg.setFont(QtGui.QFont("Arial", 20))

# group_box_2 for bat

        self.Bat_group_box_name.setText(_translate("MainWindow", "Bat Analysis"))
        self.Bat_group_box_name.setFont(QtGui.QFont("Times New Roman", 20))

        self.swing_time_lb.setText(_translate("MainWindow", "swing time"))
        self.swing_time_lb.setFont(QtGui.QFont("Times New Roman", 20))

        self.bat_speed_lb.setText(_translate("MainWindow", "bat speed"))
        self.bat_speed_lb.setFont(QtGui.QFont("Times New Roman", 20))

        self.Ball_group_box_name.setText(_translate("MainWindow", "Ball Analysis"))
        self.Ball_group_box_name.setFont(QtGui.QFont("Times New Roman", 20))


        self.swing_angle_lb.setText(_translate("MainWindow", "bat angle"))
        self.swing_angle_lb.setFont(QtGui.QFont("Times New Roman",20))

        self.ball_exit_angle_lb.setText(_translate("MainWindow", "exit angle"))
        self.ball_exit_angle_lb.setFont(QtGui.QFont("Times New Roman", 20))

        self.ball_exit_speed_lb.setText(_translate("MainWindow", "exit speed"))
        self.ball_exit_speed_lb.setFont(QtGui.QFont("Times New Roman", 20))

        self.projected_dis_lb.setText(_translate("MainWindow", "projected distance"))
        self.projected_dis_lb.setFont(QtGui.QFont("Times New Roman", 20))


        self.swing_time_lb_outcome.setText(_translate("MainWindow", ""))
        self.swing_time_lb_outcome.setFont(QtGui.QFont("Times New Roman", 20))

        self.bat_speed_lb_outcome.setText(_translate("MainWindow", ""))
        self.bat_speed_lb_outcome.setFont(QtGui.QFont("Times New Roman", 20))

        self.ball_exit_angle_lb_outcome.setText(_translate("MainWindow", ""))
        self.ball_exit_angle_lb_outcome.setFont(QtGui.QFont("Times New Roman", 20))

        self.ball_exit_speed_lb_outcome.setText(_translate("MainWindow", ""))
        self.ball_exit_speed_lb_outcome.setFont(QtGui.QFont("Times New Roman", 20))

        self.projected_dis_lb_outcome.setText(_translate("MainWindow", ""))
        self.projected_dis_lb_outcome.setFont(QtGui.QFont("Times New Roman", 20))

        self.swing_angle_lb_outcome.setText(_translate("MainWindow", ""))
        self.swing_angle_lb_outcome.setFont(QtGui.QFont("Times New Roman",20))

        self.projected_dis_lb_outcome_unit.setText(_translate("MainWindow", "ft"))
        self.projected_dis_lb_outcome_unit.setFont(QtGui.QFont("Times New Roman",20))

        self.swing_time_lb_outcome_unit.setText(_translate("MainWindow", "s"))
        self.swing_time_lb_outcome_unit.setFont(QtGui.QFont("Times New Roman", 20))

        self.bat_speed_lb_outcome_unit.setText(_translate("MainWindow", "mph"))
        self.bat_speed_lb_outcome_unit.setFont(QtGui.QFont("Times New Roman", 20))

        self.ball_exit_angle_lb_outcome_unit.setText(_translate("MainWindow", "degree"))
        self.ball_exit_angle_lb_outcome_unit.setFont(QtGui.QFont("Times New Roman", 20))

        self.ball_exit_speed_lb_outcome_unit.setText(_translate("MainWindow", "mph"))
        self.ball_exit_speed_lb_outcome_unit.setFont(QtGui.QFont("Times New Roman", 20))

        self.swing_angle_lb_outcome_unit.setText(_translate("MainWindow", "degree"))
        self.swing_angle_lb_outcome_unit.setFont(QtGui.QFont("Times New Roman",20))


        # self.label_framecnt.setText(_translate("MainWindow", "frame"))
        # self.label_framecnt.setFont(QtGui.QFont("Arial", 20))

        # self.framecnt.setFont(QtGui.QFont("Arial", 20))
        # self.totalcnt.setFont(QtGui.QFont("Arial", 20))
        
        # self.label_framecnt2.setText(_translate("MainWindow", "frame"))
        # self.label_framecnt2.setFont(QtGui.QFont("Arial", 20))

        # self.framecnt2.setFont(QtGui.QFont("Arial", 20))
        # self.totalcnt2.setFont(QtGui.QFont("Arial", 20))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
